import { Component, inject } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-legal',
  standalone: true,
  templateUrl: './legal.component.html',
  styleUrl: './legal.component.css'
})
export class LegalComponent {
  private route = inject(ActivatedRoute);
  type = this.route.snapshot.data['type'] as 'privacy' | 'terms';

  get title(): string {
    return this.type === 'privacy' ? 'Aviso de privacidad' : 'Terminos y condiciones';
  }

  get sections() {
    if (this.type === 'privacy') {
      return [
        ['1. Identidad y domicilio del responsable', 'La presente plataforma de comercio electronico especializada en la venta de maquinas, accesorios y equipo de gimnasio sera responsable del tratamiento de los datos personales proporcionados por los usuarios. Para efectos del presente aviso de privacidad, la plataforma podra ser contactada mediante los canales oficiales de atencion al cliente disponibles dentro del sitio web.'],
        ['2. Datos personales que se recopilan', 'La plataforma podra recopilar nombre completo, correo electronico, numero telefonico, direccion de entrega, datos de facturacion cuando sean necesarios, informacion de cuenta como nombre de usuario y contrasena protegida, historial de compras, informacion relacionada con pedidos, pagos, entregas, garantias, cambios, devoluciones y reportes, asi como evidencia enviada por el usuario, como fotografias o videos de productos danados, incompletos o defectuosos. La plataforma no solicitara datos personales sensibles, como informacion medica, religiosa, politica, biometrica o de salud, salvo que en el futuro sea estrictamente necesario y se solicite el consentimiento correspondiente.'],
        ['3. Finalidades del tratamiento de datos personales', 'Los datos personales del usuario seran utilizados para crear y administrar cuentas de usuario, validar la identidad del usuario dentro de la plataforma, procesar compras realizadas mediante el carrito de compras, confirmar pagos y registrar pedidos, gestionar el historial de compras, coordinar entregas con proveedores o empresas de paqueteria, dar seguimiento a pedidos, retrasos, productos incompletos, danados o defectuosos, gestionar garantias, cambios, devoluciones y cancelaciones, brindar atencion al cliente, proteger la seguridad de la plataforma, las cuentas de usuario y las transacciones, detectar accesos no autorizados, intentos de vulneracion o uso indebido de cuentas. Ademas, los datos podran utilizarse para finalidades secundarias como enviar promociones, descuentos o informacion comercial relacionada con productos fitness, mejorar la experiencia de usuario dentro de la plataforma, analizar el rendimiento del catalogo, ventas, inventario y servicios, y realizar encuestas de satisfaccion o retroalimentacion. El usuario podra solicitar que sus datos no sean utilizados para finalidades secundarias mediante los canales de atencion de la plataforma.'],
        ['4. Uso de datos para pagos', 'Las compras realizadas dentro de la plataforma podran procesarse mediante pasarelas de pago externas. La plataforma podra utilizar la informacion necesaria para validar el pago, confirmar la compra y registrar el pedido. Sin embargo, los datos bancarios o de tarjeta podran ser tratados directamente por la pasarela de pago correspondiente, conforme a sus propias politicas de privacidad y seguridad. La plataforma no debera almacenar datos bancarios completos del usuario, salvo que la pasarela de pago o la legislacion aplicable lo permita bajo medidas de seguridad adecuadas.'],
        ['5. Transferencia de datos personales', 'La plataforma podra compartir los datos personales estrictamente necesarios con terceros relacionados con la operacion del servicio, tales como proveedores de productos, fabricantes, empresas de paqueteria, servicios de entrega, pasarelas de pago, servicios de facturacion, servicios de hosting o infraestructura tecnologica, soporte tecnico o mantenimiento de la plataforma. Estas transferencias tendran como finalidad procesar compras, validar pagos, coordinar entregas, gestionar garantias, resolver reportes y mantener el funcionamiento de la plataforma. En toda transferencia de datos personales, el responsable debe comunicar al receptor el aviso de privacidad bajo el cual se tratan los datos.'],
        ['6. Proteccion y seguridad de los datos', 'La plataforma implementara medidas tecnicas, administrativas y de seguridad para proteger los datos personales de los usuarios contra perdida, alteracion, acceso no autorizado, uso indebido o divulgacion no permitida. Entre estas medidas podran incluirse mecanismos de autenticacion, proteccion de contrasenas mediante funciones hash, control de accesos, respaldos, monitoreo de actividad y actualizaciones de seguridad. Sin embargo, ningun sistema digital puede garantizar seguridad absoluta, por lo que la plataforma podra realizar mejoras, revisiones y actualizaciones para reducir riesgos tecnicos u operativos.'],
        ['7. Conservacion de los datos personales', 'Los datos personales se conservaran durante el tiempo necesario para cumplir con las finalidades descritas en este aviso de privacidad. La informacion relacionada con pedidos, pagos, garantias, devoluciones, facturacion o atencion al cliente podra conservarse por el tiempo necesario para cumplir obligaciones legales, administrativas, fiscales o comerciales. Una vez que los datos dejen de ser necesarios, podran ser eliminados, bloqueados o anonimizados conforme a los procedimientos internos de la plataforma.'],
        ['8. Derechos del usuario', 'El usuario podra solicitar el acceso, rectificacion, cancelacion u oposicion al tratamiento de sus datos personales. Esto significa que el usuario podra conocer que datos personales tiene la plataforma, solicitar la correccion de datos incorrectos o desactualizados, solicitar la eliminacion de datos cuando sea procedente, oponerse al uso de sus datos para determinadas finalidades y revocar su consentimiento para el tratamiento de sus datos personales, cuando legalmente sea posible. Para ejercer estos derechos, el usuario debera enviar una solicitud mediante los canales oficiales de atencion al cliente de la plataforma.'],
        ['9. Uso de cookies y tecnologias similares', 'La plataforma podra utilizar cookies u otras tecnologias similares para mejorar la experiencia de navegacion, recordar preferencias del usuario, mantener sesiones activas, analizar el rendimiento del sitio y mejorar el funcionamiento del catalogo. El usuario podra configurar su navegador para rechazar o eliminar cookies. Sin embargo, algunas funciones de la plataforma podrian no operar correctamente si estas tecnologias son deshabilitadas.'],
        ['10. Menores de edad', 'La plataforma esta dirigida principalmente a personas con capacidad legal para realizar compras en linea. En caso de que un menor de edad utilice la plataforma, debera contar con autorizacion de su madre, padre o tutor legal para registrarse o realizar compras.'],
        ['11. Cambios al aviso de privacidad', 'La plataforma podra modificar este aviso de privacidad cuando sea necesario por cambios legales, tecnicos, operativos, comerciales o de funcionamiento. Cualquier modificacion estara disponible dentro de la plataforma y sera aplicable a partir de su publicacion.'],
        ['12. Contacto', 'Para dudas, aclaraciones, solicitudes relacionadas con datos personales, ejercicio de derechos, revocacion de consentimiento o informacion sobre este aviso de privacidad, el usuario podra comunicarse mediante los canales oficiales de atencion al cliente disponibles en la plataforma.']
      ];
    }

    return [
      ['Uso de la plataforma', 'La plataforma funciona como una tienda virtual especializada en la venta de maquinas, accesorios y equipo de gimnasio, dirigida a usuarios de home gym, gimnasios independientes y clientes interesados en productos fitness. Al acceder, registrarse o realizar una compra dentro de la plataforma, el usuario acepta los presentes terminos y condiciones.'],
      ['Cuenta y seguridad', 'Para crear una cuenta, el usuario debera proporcionar informacion valida, incluyendo un correo electronico activo. El usuario es responsable de mantener protegidas sus credenciales de acceso y de no compartir su contrasena con terceros. La plataforma implementara mecanismos de autenticacion y proteccion de contrasenas mediante funciones hash. En caso de detectar accesos no autorizados, intentos de vulneracion o uso indebido de una cuenta, la plataforma podra bloquear temporalmente el acceso o tomar medidas de seguridad adicionales.'],
      ['Catalogo de productos', 'Los productos se mostraran dentro de un catalogo digital con informacion como nombre, precio, descripcion, imagen, categoria, disponibilidad y caracteristicas generales. La plataforma procurara mantener actualizada la informacion del catalogo. Sin embargo, la disponibilidad de productos puede variar por cambios de inventario, retrasos de proveedores, errores de sistema o alta demanda. Las imagenes son de caracter ilustrativo y pueden presentar diferencias menores respecto al producto final entregado.'],
      ['Compras, pagos y pedidos', 'Las compras podran realizarse mediante el carrito de compras y las pasarelas de pago integradas. Todo pedido estara sujeto a validacion de datos, confirmacion de pago y existencia de inventario. La compra se considerara confirmada unicamente cuando el pago haya sido aprobado y el pedido haya sido registrado correctamente en el sistema. La plataforma podra cancelar, pausar o revisar un pedido en caso de errores en el precio, falta de inventario, problemas con el pago, datos incompletos o sospecha de uso indebido.'],
      ['Precios y promociones', 'Los precios publicados podran cambiar sin previo aviso debido a variaciones de proveedores, costos de importacion, tipo de cambio, promociones temporales o ajustes comerciales. Las promociones estaran sujetas a vigencia, disponibilidad de productos y condiciones especificas indicadas dentro de la plataforma.'],
      ['Envios y entregas', 'La entrega de los productos puede depender de proveedores, empresas de paqueteria, disponibilidad de stock, ubicacion del cliente y tipo de equipo adquirido. Debido al tamano y peso de algunas maquinas de gimnasio, ciertos productos pueden requerir condiciones especiales de traslado, maniobra, recepcion o instalacion. Los tiempos de entrega seran estimados y podran variar por causas externas.'],
      ['Productos danados, incompletos o con retraso', 'En caso de recibir un producto incompleto, danado, defectuoso o en mal estado, el usuario debera reportarlo mediante los canales de atencion de la plataforma. El reporte debera incluir informacion del pedido, descripcion del problema y, cuando sea posible, evidencia como fotografias o videos del producto recibido. La plataforma dara seguimiento al caso con el proveedor o empresa de paqueteria correspondiente.'],
      ['Cancelaciones, cambios y devoluciones', 'Las solicitudes de cancelacion, cambio o devolucion estaran sujetas al estado del pedido, condiciones del producto, tiempo transcurrido desde la entrega, politicas del proveedor y comprobante de compra. No podran aceptarse devoluciones de productos danados por mal uso, instalacion incorrecta, modificaciones no autorizadas, desgaste normal, golpes, humedad o uso distinto al recomendado.'],
      ['Garantias', 'Los productos podran contar con garantia del fabricante, proveedor o vendedor, segun corresponda. La garantia podra cubrir defectos de fabricacion o fallas derivadas del funcionamiento normal del producto. La garantia no cubrira danos ocasionados por uso incorrecto, sobrecarga, instalacion inadecuada, falta de mantenimiento, modificaciones no autorizadas o uso contrario a las indicaciones del fabricante.'],
      ['Uso responsable del equipo', 'El usuario reconoce que las maquinas y accesorios de gimnasio deben utilizarse de forma responsable, siguiendo manuales, advertencias de seguridad, instrucciones de instalacion y recomendaciones del fabricante. La plataforma no sera responsable por lesiones, accidentes o danos derivados del uso incorrecto del equipo, falta de supervision, instalacion inadecuada o uso distinto al recomendado.'],
      ['Datos personales', 'Al registrarse o realizar una compra, el usuario autoriza el uso de sus datos personales para gestionar su cuenta, procesar pedidos, validar pagos, generar historial de compras, coordinar entregas y brindar atencion al cliente. La plataforma debera manejar esta informacion conforme a la legislacion aplicable en materia de proteccion de datos personales y poner a disposicion del usuario un aviso de privacidad.'],
      ['Seguridad de la plataforma', 'La plataforma implementara medidas de seguridad para proteger la informacion de los usuarios, las credenciales de acceso, los pedidos y las transacciones realizadas. Sin embargo, ningun sistema digital puede garantizar seguridad absoluta. Por ello, la plataforma podra realizar actualizaciones, revisiones, pruebas y mejoras para reducir riesgos de accesos no autorizados, errores tecnicos o fallas operativas.'],
      ['Disponibilidad del servicio', 'La plataforma podra recibir mantenimiento, pruebas, actualizaciones o mejoras para optimizar su rendimiento, seguridad, catalogo, pagos, inventario y experiencia de usuario. Durante estos procesos, algunas funciones podrian no estar disponibles temporalmente. La plataforma procurara reducir interrupciones, pero no garantiza disponibilidad continua o libre de errores.'],
      ['Proveedores y empresas externas', 'La plataforma podra trabajar con proveedores, fabricantes, empresas de paqueteria y pasarelas de pago externas para completar la venta, entrega y gestion de los productos. Algunos retrasos, errores de entrega, fallas de stock o problemas de pago pueden depender de terceros. En estos casos, la plataforma dara seguimiento al problema, pero la solucion podra estar sujeta a los tiempos y politicas del proveedor correspondiente.'],
      ['Propiedad intelectual', 'Los textos, imagenes, logotipos, diseno, estructura, interfaz y contenido de la plataforma pertenecen a sus respectivos titulares y no podran copiarse, modificarse, distribuirse o utilizarse sin autorizacion.'],
      ['Modificaciones a los terminos', 'La plataforma podra modificar estos terminos y condiciones cuando sea necesario por cambios operativos, tecnicos, comerciales o legales. Las modificaciones estaran disponibles dentro de la plataforma y seran aplicables a partir de su publicacion.'],
      ['Atencion al cliente', 'El usuario podra comunicarse con la plataforma para dudas, aclaraciones, problemas con pedidos, garantias, devoluciones, pagos o reportes relacionados con productos mediante los canales oficiales de atencion al cliente.']
    ];
  }
}
